name: Multi-Machine Workflowzz

on:
  push:
    branches:
      - main

jobs:
  run-on-ubuntu1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program_number: [1,2,3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Run Python Program
        continue-on-error: true
        run: |
          pip install requests beautifulsoup4 colorama fake-useragent
          wget https://github.com/Mosnio/dpy/raw/main/fl${{ matrix.program_number }}.py
          ls
          python fl${{ matrix.program_number }}.py

  run-on-ubuntu4:
    needs: run-on-ubuntu3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program_number: [1,2,3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Run Python Program
        continue-on-error: true
        run: |
          pip install requests beautifulsoup4 colorama fake-useragent
          wget https://github.com/Mosnio/dpy/raw/main/fl${{ matrix.program_number }}.py
          ls
          python fl${{ matrix.program_number }}.py

  run-on-ubuntu3:
    needs: run-on-ubuntu2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program_number: [1,2,3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Run Python Program
        continue-on-error: true
        run: |
          pip install requests beautifulsoup4 colorama fake-useragent
          wget https://github.com/Mosnio/dpy/raw/main/fl${{ matrix.program_number }}.py
          ls
          python fl${{ matrix.program_number }}.py
          

  run-on-ubuntu2:
    needs: run-on-ubuntu1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program_number: [1,2,3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Run Python Program
        continue-on-error: true
        run: |
          pip install requests beautifulsoup4 colorama fake-useragent
          wget https://github.com/Mosnio/dpy/raw/main/fl${{ matrix.program_number }}.py
          ls
          python fl${{ matrix.program_number }}.py
