on:
  push:
name: hhsgu

jobs:
  run_1:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://github.com/Mosnio/mehi1/raw/main/clmb/bot.php
        wget https://github.com/Mosnio/mehi1/raw/main/clmb/Url-solvemedia
        wget https://github.com/Mosnio/mehi1/raw/main/clmb/data.json
        echo -e "1"|php bot.php
